# Generated by Django 6.1 on 2026-08-10 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalDataConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=10, verbose_name="Версия согласия"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(max_length=64, verbose_name="Хэш текста согласия"),
                ),
                (
                    "consented_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата предоставления"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адрес"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="User-Agent",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_data_consent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Согласие на обработку ПД",
                "verbose_name_plural": "Согласия на обработку ПД",
                "ordering": ["-consented_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "version"],
                        name="users_perso_user_id_15f4e6_idx",
                    )
                ],
            },
        ),
    ]
