# Generated by Django 4.2.11 on 2026-09-29 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Например: Дом, Офис, Дача', max_length=50, verbose_name='Метка')),
                ('full_address', models.CharField(help_text='Полный адрес из геокодера Яндекс (например: Самара ул Революционная 3)', max_length=500, verbose_name='Полный адрес')),
                ('coordinates', models.CharField(blank=True, default='', help_text='Координаты адреса в формате longitude,latitude', max_length=50, verbose_name='Координаты [lon,lat]')),
                ('apartment', models.CharField(blank=True, default='', max_length=50, verbose_name='Квартира/офис')),
                ('is_default', models.BooleanField(default=False, help_text='Используется по умолчанию при оформлении заказа', verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='users_deliv_user_id_6dee78_idx')],
            },
        ),
    ]
