# Generated by Django 4.2.11 on 2026-10-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время подтверждения email. OAuth-пользователи отмечаются автоматически.', null=True, verbose_name='Email подтверждён в'),
        ),
    ]
