# Generated by Django 4.2.11 on 2026-10-06 17:50

from django.db import migrations


def forward_fill_email_verified_at(apps, schema_editor):
    """Копируем статус is_used из UserEmailVerification в UserProfile."""
    UserEmailVerification = apps.get_model('users', 'UserEmailVerification')
    UserProfile = apps.get_model('users', 'UserProfile')

    for verification in UserEmailVerification.objects.filter(is_used=True):
        try:
            profile = verification.user.profile
        except UserProfile.DoesNotExist:
            continue
        if profile.email_verified_at is None:
            profile.email_verified_at = verification.created_at
            profile.save(update_fields=['email_verified_at'])


def reverse_fill_email_verified_at(apps, schema_editor):
    """Откат: очищаем email_verified_at."""
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.filter(email_verified_at__isnull=False).update(
        email_verified_at=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_email_verified_at_to_userprofile'),
    ]

    operations = [
        migrations.RunPython(
            forward_fill_email_verified_at,
            reverse_fill_email_verified_at,
        ),
    ]
