# Generated by Django 4.2.11 on 2026-08-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_review_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='catalog_cat_slug_695af4_idx',
            old_name='catalog_categor_slug_4f3e8a_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='catalog_cat_parent__e2d7e1_idx',
            old_name='catalog_categor_parent_i_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_slug_2b1eb6_idx',
            old_name='catalog_product_slug_1234ab_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_categor_ac86d2_idx',
            old_name='catalog_product_categor_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_stock_4de222_idx',
            old_name='catalog_product_stock_9876ef_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_roast_l_56a0cc_idx',
            old_name='catalog_product_roast_5544dd_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_sca_sco_e4f3c1_idx',
            old_name='catalog_product_sca_33eeff_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='catalog_rev_product_837d25_idx',
            old_name='catalog_review_product_77aabb_idx',
        ),
    ]
