# Generated by Django 4.2.11 on 2026-10-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_price_per_50g'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.IntegerField(default=0, verbose_name='Вес товара (г)'),
        ),
    ]
