# Generated by Django 4.2.11 on 2026-08-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-start_date']},
        ),
        migrations.RenameIndex(
            model_name='news',
            new_name='news_news_slug_915ecd_idx',
            old_name='news_news_slug_5e4f7a2a_indices',
        ),
        migrations.RenameIndex(
            model_name='news',
            new_name='news_news_is_publ_509731_idx',
            old_name='news_news_is_pub_e8f2a1b4_indices',
        ),
        migrations.RenameIndex(
            model_name='promotion',
            new_name='news_promot_is_acti_8c62e6_idx',
            old_name='news_pro_is_acti_8f3c8e_indices',
        ),
    ]
