# Generated by Django 4.2.11 on 2026-08-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_awaiting_payment_status_and_reserved_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_c6dd84_idx',
            old_name='orders_order_status_123abc_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_user_id_02a211_idx',
            old_name='orders_order_user_id_456def_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_created_0e92de_idx',
            old_name='orders_order_created_789ghi_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_order_i_52f79a_idx',
            old_name='orders_orderitem_order_id_abc123_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('awaiting_payment', 'Ожидает оплаты'), ('in_progress', 'В обработке'), ('ready', 'Готов'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа в ЮКассе'),
        ),
    ]
