# Generated by Django 4.2.11 on 2026-08-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_orders_order_status_123abc_idx_orders_orde_status_c6dd84_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yandex_access_token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='OAuth токен Яндекс Доставки'),
        ),
    ]
