# Generated by Django 4.2.11 on 2026-08-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_yandex_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yandex_merchant_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Merchant ID Яндекс Доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='yandex_station_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='platform_station_id (ПВЗ/склад)'),
        ),
        migrations.AddField(
            model_name='order',
            name='yandex_station_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название точки доставки'),
        ),
    ]
