# Generated by Django 4.2.11 on 2026-08-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_yandex_merchant_id_order_yandex_station_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('access_token', models.CharField(blank=True, max_length=500, verbose_name='Access Token')),
                ('refresh_token', models.CharField(blank=True, max_length=500, verbose_name='Refresh Token')),
                ('yandex_account_id', models.CharField(blank=True, max_length=100, verbose_name='Yandex Account ID')),
                ('merchant_id', models.CharField(blank=True, max_length=100, verbose_name='Merchant ID')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Аккаунт мерчанта',
                'verbose_name_plural': 'Аккаунты мерчантов',
                'ordering': ['-created_at'],
            },
        ),
    ]
