# Generated by Django 4.2.11 on 2026-08-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rewrite_yandex_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='package',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='yandex_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID заказа в Cargo API'),
        ),
    ]
