# Generated by Django 4.2.11 on 2026-09-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_express_other_day_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yandex_offer_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID оффера Яндекс Доставки (Other Day API)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа в платёжной системе'),
        ),
    ]
